# Generated by Django 3.0.8 on 2020-07-14 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20200714_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.User')),
                ('inst_user_id', models.PositiveIntegerField()),
                ('long_lived_token', models.CharField(blank=True, max_length=255)),
                ('expires_in', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
