# Generated by Django 3.0.8 on 2020-07-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccount',
            name='expires_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='inst_user_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='long_lived_token',
            field=models.CharField(max_length=255),
        ),
    ]
