# Generated by Django 3.0.8 on 2020-07-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_update_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
